# Generated by Django 5.0.14 on 2025-05-08 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('uni_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('EXCUSED', 'EXCUSED'), ('UNEXCUSED', 'UNEXCUSED'), ('SCHEDULED', 'SCHEDULED')], max_length=255)),
                ('reason', models.CharField(max_length=200)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intern')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_id', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=20)),
                ('est_time', models.FloatField()),
                ('act_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('Done', 'Done')], default='To Do', max_length=255)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intern')),
            ],
        ),
    ]
