# Generated by Django 5.0.14 on 2025-06-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='absence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='intern',
            table=None,
        ),
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
