# Generated by Django 5.0.14 on 2025-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
