# Generated by Django 5.0.14 on 2025-05-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_project_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
